"""add issue_date and payment_date indexes for dashboard

Revision ID: 2e1e85c3b7cc
Revises: 664a87dd2865
Create Date: 2026-09-17 20:06:35.863361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e1e85c3b7cc'
down_revision: Union[str, None] = '664a87dd2865'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_invoices_issue_date', 'invoices', ['issue_date'], unique=False)
    op.create_index('idx_payments_payment_date', 'payments', ['payment_date'], unique=False)
    op.create_index('idx_quotes_issue_date', 'quotes', ['issue_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_quotes_issue_date', table_name='quotes')
    op.drop_index('idx_payments_payment_date', table_name='payments')
    op.drop_index('idx_invoices_issue_date', table_name='invoices')
    # ### end Alembic commands ###
