"""initial schema

Revision ID: 664a87dd2865
Revises:
Create Date: 2026-09-16 07:04:57.308834

"""
from datetime import datetime
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '664a87dd2865'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('contact_person', sa.String(), nullable=True),
    sa.Column('contact_info', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('business_name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('contact_info', sa.String(), nullable=True),
    sa.Column('invoice_registration_number', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_company_profile_single_row'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('expense_date', sa.String(), nullable=False),
    sa.Column('account_category', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('tax_category', sa.String(), nullable=False),
    sa.Column('payee', sa.String(), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('memo', sa.String(), nullable=True),
    sa.Column('attachment_path', sa.String(), nullable=True),
    sa.Column('attachment_original_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.CheckConstraint("payment_method IN ('CASH','CREDIT_CARD','BANK_TRANSFER','OTHER') OR payment_method IS NULL", name='ck_expenses_payment_method'),
    sa.CheckConstraint("tax_category IN ('STANDARD_10','NON_TAXABLE','OUT_OF_SCOPE','NOT_APPLICABLE')", name='ck_expenses_tax_category'),
    sa.CheckConstraint('amount > 0', name='ck_expenses_amount'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_expenses_account_category', 'expenses', ['account_category'], unique=False)
    op.create_index('idx_expenses_expense_date', 'expenses', ['expense_date'], unique=False)
    op.create_table('quotes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quote_number', sa.String(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('issue_date', sa.String(), nullable=True),
    sa.Column('expiry_date', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('subtotal_amount', sa.Integer(), nullable=False),
    sa.Column('tax_amount', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Integer(), nullable=False),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT','CONFIRMED')", name='ck_quotes_status'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quote_number')
    )
    op.create_index('idx_quotes_client_id', 'quotes', ['client_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invoice_number', sa.String(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('issue_date', sa.String(), nullable=True),
    sa.Column('due_date', sa.String(), nullable=True),
    sa.Column('source_quote_id', sa.Integer(), nullable=True),
    sa.Column('subtotal_amount', sa.Integer(), nullable=False),
    sa.Column('tax_amount', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Integer(), nullable=False),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['source_quote_id'], ['quotes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number'),
    sa.UniqueConstraint('source_quote_id')
    )
    op.create_index('idx_invoices_client_id', 'invoices', ['client_id'], unique=False)
    op.create_table('quote_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.Column('tax_category', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.CheckConstraint("tax_category IN ('STANDARD_10','NON_TAXABLE','OUT_OF_SCOPE')", name='ck_quote_items_tax_category'),
    sa.CheckConstraint('quantity > 0', name='ck_quote_items_quantity'),
    sa.CheckConstraint('unit_price > 0', name='ck_quote_items_unit_price'),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_quote_items_quote_id', 'quote_items', ['quote_id'], unique=False)
    op.create_table('invoice_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.Column('tax_category', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.CheckConstraint("tax_category IN ('STANDARD_10','NON_TAXABLE','OUT_OF_SCOPE')", name='ck_invoice_items_tax_category'),
    sa.CheckConstraint('quantity > 0', name='ck_invoice_items_quantity'),
    sa.CheckConstraint('unit_price > 0', name='ck_invoice_items_unit_price'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_invoice_items_invoice_id', 'invoice_items', ['invoice_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_payments_amount'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_payments_invoice_id', 'payments', ['invoice_id'], unique=False)
    # ### end Alembic commands ###

    # 詳細設計書6.3章: company_profileはid=1固定の単一行。初期データとして空レコードを投入する。
    company_profile_table = sa.table(
        "company_profile",
        sa.column("id", sa.Integer),
        sa.column("name", sa.String),
        sa.column("business_name", sa.String),
        sa.column("address", sa.String),
        sa.column("contact_info", sa.String),
        sa.column("invoice_registration_number", sa.String),
        sa.column("updated_at", sa.String),
    )
    op.bulk_insert(
        company_profile_table,
        [
            {
                "id": 1,
                "name": "",
                "business_name": None,
                "address": None,
                "contact_info": None,
                "invoice_registration_number": None,
                "updated_at": datetime.now().isoformat(timespec="seconds"),
            }
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_payments_invoice_id', table_name='payments')
    op.drop_table('payments')
    op.drop_index('idx_invoice_items_invoice_id', table_name='invoice_items')
    op.drop_table('invoice_items')
    op.drop_index('idx_quote_items_quote_id', table_name='quote_items')
    op.drop_table('quote_items')
    op.drop_index('idx_invoices_client_id', table_name='invoices')
    op.drop_table('invoices')
    op.drop_index('idx_quotes_client_id', table_name='quotes')
    op.drop_table('quotes')
    op.drop_index('idx_expenses_expense_date', table_name='expenses')
    op.drop_index('idx_expenses_account_category', table_name='expenses')
    op.drop_table('expenses')
    op.drop_table('company_profile')
    op.drop_table('clients')
    # ### end Alembic commands ###
